# Generated by Django 5.2.4 on 2025-08-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
