# Generated by Django 5.2.4 on 2025-08-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(
                blank=True,
                default=500,
                help_text="Укажите стоимость курса",
                null=True,
                verbose_name="Цена курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Укажите стоимость урока",
                null=True,
                verbose_name="Цена урока",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID сессии",
                max_length=250,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
    ]
